omnia-md/conda-recipes

openmm/build.sh
openmm/post-link.sh

Fixed post-link script to eliminate non-OSX-compatible `mv -t`

---

msmbuilder/meta.yaml

As mentioned [here](https://github.com/omnia-md/conda-recipes/issues/82#issuecomment-69391043), the msmbuilder recipe was simply pulling from the master HEAD.
I made the first "real" 3.0 [release](https://github.com/msmbuilder/msmbuilder/releases/tag/v3.0.0) of msmbuilder on github, and updated this recipe to pull that code.

Update msmbuilder to real release

---

README.md

This just adds a badge to the `README.md` to report on the travis-ci build status.

Added travis-ci badge to README.md

---

openmm/meta.yaml

I'm not 100% sure why this happens. It relates to wierd setuptools stuff like namespace packages. But this does get rid of the extra files from #104.

Fix issue with extra files in OpenMM

---

openmm/meta.yaml

I think the reason our py33 and py34 builds were failing is that we were using the ancient version of swig provided on the VM.  We have two options:
1.  `conda install swig` every time we provision a new miniconda install.  
2.  Add swig to the openmm `meta.yaml`
I've tested both of these.  Here I've implemented (2), as it's the more elegant solution.  We do have to worry about some of the strange swig path issues that were observed in some previous swig conda packages.  However, I imagine that both (1) and (2) will be affected by this equally, as anaconda seems to have only a single swig package online (swig-3.0.2-0.tar.bz2).

Add swig back into the openmm conda build requirements.

---

gaff2xml/meta.yaml

FYI: I previously had some hard-coded jenkins / travis detection coded into various nosetests.  Now that we're running several different CI frameworks, I think a more generalizable approach is as follows:
1. Tag all slow tests using @attr('slow')
2.  In all conda recipes, disable the slow tests by default (`nosetests -a '!slow'`), so that recipes can be built in a reasonable amount of time
3.  We can leave off the `-a '!slow'` flag when running tests locally 
IMHO this approach will work fairly generally for multiple packages.

Using nose.attr('slow') to handle slow tests in gaff2xml recipe

---

openmm/bld.bat
openmm/meta.yaml
openmm/openmm-pr-780.patch
openmm/post-link.bat
openmm/post-link.sh

Changes to the OpenMM recipe, bumping the build number to 2. This should ensure that the [setting of environment variables](http://docs.openmm.org/6.2.0/userguide/application.html#installing-on-windows) like the PATH or OPENMM_PLUGIN_DIR is not required on *nix or windows when installing via conda.
To do this, https://github.com/pandegroup/openmm/pull/780 is incorporated as a patch file. There is also a really horrendous post-link.(bat|sh) that modifies `site-packages/simtk/openmm/version.py` when the conda package is being so that `__init__.py` knows where to find the openmm libraries.
I'll do the merge. I still need to do more testing on windows.

OpenMM Windows + OPENMM_PLUGIN_DIR

---

yank/meta.yaml

I've added `mpi4py` (necessary if MPI runs are desired) and `pyyaml` (since we'll need it soon anyway).

Added mpi4py and pyyaml to requirements for yank.

---

openmmtools/meta.yaml

This increments the version number to the new [0.6.2 release](https://github.com/choderalab/openmmtools/releases/tag/0.6.2) and resets the build number to 0.

Updated openmmtools recipe

---

ambermini/build.sh
ambermini/meta.yaml

So this change, on my machine where I've trashed the file `libquadmath.0.dylib` from my homebrewed-gfortran, which causes the linker to statically link to libquadmath, produces a static build.
I can upload the binary to binstar.

ambermini static

---

yank/build.sh
yank/meta.yaml

This version installs examples into `anaconda/share/yank/examples/` to match https://github.com/choderalab/yank/pull/209.

Updated yank recipe to also install examples

---

conda-build-all

If you look at one of the jenkins console logs, a lot of the output is taken up by the progress bar streaming down the screen. Kind of annoying. This gets rid of it.
https://jenkins.choderalab.org/job/conda-omnia-release-linux-vagrant/54/console

Don't display progress bar in conda-build-all

---

svgwrite/bld.bat
svgwrite/build.sh
svgwrite/meta.yaml

added svgwrite to replace pip install svgwrite for `openpathsampling`
A build package has already been added to `binstar/omnia`
The recipe was built using `conda skeleton` but I had to remove the `svgwrite/data` import for testing.
The package seems to load correctly.

added conda recipe for svgwrite

---

conda-build-all

Add a flag to conda-build-all to enable upload direct to binstar upon completion of each build:
usage: $ python conda-build-all --upload omnia --token $BINSTAR_TOKEN ...
(fixed #191)

Binstar upload

---

appveyor.yml

I'm trying this one step at a time.

Enable 64-bit python builds in Appveyor

---

openmm-dev/build.sh
openmm-dev/meta.yaml

This replicates the fix from #176 for `openmm-dev`

Updated openmm-dev recipe to use 10.7 SDK on osx builds.

---

openmoltools/meta.yaml

0.6.7 release adds some GROMACS support to openmoltools, as well as fixing some issues with error checking of AMBER tools and reorganization of AMBER-related functionality.

Update openmoltools meta.yaml for 0.6.7 release

---

mdtraj/meta.yaml

Cut bugfix release of MDTraj to fix the tables bug. (Note I skipped 1.4.1 because I already used that point release on PyPI to correct a mistake in build the sdist earlier).

MDTraj 1.4.2

---

pymbar/meta.yaml

This updates pymbar to 3.0.0.beta2 to fix some failing win conda package builds.

[pymbar] Updated to 3.0.0.beta2

---

openmoltools/meta.yaml

This point release is needed for ParmEd 2.0 compatibility, among other things.

Update openmoltools for 0.6.8 point release

---

openmoltools/meta.yaml

@jchodera - looks like @kylebeauchamp forgot to add parmed as a requirement in the omnia conda recipe when he added it as a requirement for travis in the package itself, hence the problem here. It's not clear to me why this didn't cause problems sooner, since `utils` has been trying to import `parmed` for a while.

Fix openmoltools conda recipe to add parmed

---

conda-build-all

Modifies `conda-build-all` to find conda_build not by taking the first thing in the path, but by looking adjacent to the python interpreter used to invoke the script. The reason for this is, on windows, that I have both a 64-bit and 32-bit conda installed. Only the 64-bit interpreter is in my `PATH`. This way, I can do `C:\Path\To\32\bit\python.exe conda-build-all <packages>`, and it will invoke the correct copy of conda_build (the 32-bit one), even though it's not in my path.

Find the appropriate version of conda_build

---

ensembler/meta.yaml

Removes mpi4py as a dependency. This should fix issues with Jenkins OS X build.

Ensembler v1.0.1 release

---

conda-build-all

This PR updates `conda-build-all` to handle cases where multiple recipe directories might encode different versions of the same package (like pymbar2, pymbar3).

Update conda-build-all for multiple recipes for same package

---

devtools/appveyor/install.ps1

Latest release of conda-build (1.17.0) fixes the root cause of #242 upstream, so uninstalling jinja2 should not be necessary.
This reverts commit 2ed5a3e6ffd71644e90443714774b80a7e1c744a.

Revert "No jinja2/markupsafe on appveyor?"

---

msmbuilder/meta.yaml

Not all of the test suite dependencies are installed, and it takes a long time.

Disable full MSMBuilder test suite in conda-recipes

---

openmoltools/meta.yaml

Updating for new 0.6.9 release of openmoltools.
Additionally, standardizing run/build requirements with those within the project itself.

Update for openmoltools 0.6.9 / standard requirements

---

msmtools/meta.yaml

Fixes
```
[snip]
File "__init__.pxd", line 155, in init msmtools.estimation.dense.mle_trev_given_pi (msmtools/estimation/dense/mle_trev_given_pi.c:4431)
ValueError: numpy.dtype has the wrong size, try recompiling
```

MSMTools links against numpy C API

---

rdkit/.gitignore
rdkit/avalon_reaccsio.c
rdkit/bld.bat
rdkit/build.sh
rdkit/fetch_avalontools.py
rdkit/fetch_inchi.py
rdkit/meta.yaml
rdkit/rdconfig.patch
rdkit/rdpaths.patch
rdkit/utils.py

This PR adds a recipe for rdkit makes some minor modifications to the standard conda-rdkit recipe at https://github.com/rdkit/conda-rdkit (addresses #381). Namely,
1. The hard-coded requirement for boost == 1.56.0 is removed.
2. A passing test suite is no longer required for a successful build (I've noticed that one test out of 81 can be quite flaky, and I've been disabling it in practice)

RDKit Recipe

---

boost/build.sh
boost/meta.yaml
rdkit/build.sh
rdkit/meta.yaml

Statically linking to boost seems to fix the OS X issue, but it will also be much easier from a compatibility perspective.

Fixed RDKit for OS X

---

msmbuilder/meta.yaml

This should actually fix all the sklearn 0.17 issues
https://github.com/msmbuilder/msmbuilder/issues/694

Release msmbuilder 3.3.1

---

conda-build-all

I had accidentally screwed up the logic in #413

Fix logic in reporting when package fails to build

---

sphinxcontrib-autodoc_doxygen/meta.yaml
sphinxcontrib-lunrsearch/meta.yaml

Apparently, we [can't build `noarch` packages on `win`](https://ci.appveyor.com/project/rmcgibbo/conda-recipes/build/1.0.572/job/fp2wviopka3jae69#L390):
```
[noarch_python] Error: Python noarch packages can currently not be created on Windows systems.
```
This PR skips builds of the new `sphinxcontrib-*` packages on `win`.

Skip building sphinxcontrib packages on win

---

conda-build-all

This adds a `--force` flag to `conda-build-all` to allow us to force uploads to replace existing packages.

Add --force flag to conda-build-all

---

numdifftools/meta.yaml

Current version tries to pull in matplotlib, which is not listed as a dependency.
They changed it so it doesn't import matplotlib at all (yay!) https://github.com/pbrod/numdifftools/commit/79241cd0454b36e057b0ba7424f1a66c607c5228

Upgrade numdifftools to 0.9.14

---

deepchem/meta.yaml
theano/meta.yaml

The deepchem tests seem to break for an obscure CentOS reason (the nosetests for the deepchem github repo pass just fine). I'm going to disable the deepchem tests for now since this issue shouldn't affect the majority of users and I'd like to get the package up on anaconda. I've also added a git hash for theano.

Remove deepchem tests

---

mdtraj/meta.yaml

I also updated the build and run dependencies to match the meta.yaml we use for CI testing (under the assumption that those requirements are correct)

Release mdtraj 1.6

---

conda-build-all

Fix conda-build-all to not die when checking is_prerelease

---

ambermini/meta.yaml
packmol/build.sh
packmol/meta.yaml

cc: https://github.com/choderalab/openmoltools/pull/198#issuecomment-192029702

[ambermini and packmol] Update ambermini and packmol builds to fix `GFORTRAN_1.4' not found 

---

packmol/build.sh

The parallel build was segfaulting on `osx`

[packmol] Switch to serial build

---

.gitignore
shiftx2/build.sh
shiftx2/gcc.patch
shiftx2/meta.yaml

The full build requires `javac`, which will probably fail here, but the majority of the resulting package works
This is used in mdtraj testing

Add shiftx2 recipe

---

conda-build-all

#468 broke conda-dev-recipes which didn't have a file called `.pre_black_listed`.

Check if .pre_black_listed is available before trying to open it

---

openmm/meta.yaml

Downgrading to 3.3.3 broke the builds on Windows.

Use FFTW 3.3.4 on Windows

---

ensembler/meta.yaml

There is some strange problem with MODELLER 9.15 that we're still sorting out:
```
Fetching packages ...
modeller-9.15- 100% |###############################################################################################################################################################################################################################################################| Time: 0:00:00  29.78 MB/s
modeller-9.15- 100% |###############################################################################################################################################################################################################################################################| Time: 0:00:00  20.94 MB/s
modeller-9.15- 100% |################################################################## …
```

[ensembler] Update to use modeller 9.16

---

funcsigs/bld.bat
funcsigs/build.sh
funcsigs/meta.yaml
funcsigs/ordereddict.patch

Background for this the hassle with Python-2.7 and the funcsigs package on conda:main, which falsely depends on ordereddict (which is not needed for Python > 2.6).
This ugly bug silently brakes conda-build.
https://github.com/conda/conda-build/issues/879

added funcsigs package with patch to circumvent ordereddict dependency

---

openmm-example-plugin/build.sh
openmm-example-plugin/meta.yaml

This adds the example plugin. 
While this doesn't add any useful end-functionality, I think it could be helpful to catch any changes that break plugins.
There is no windows build, as I'm unsure how to set that up correctly.

Add openmm-example-plugin

---

devtools/check-outdated
graphviz/meta.yaml

```
$ devtools/check-outdated
autograd-1.1.2 outdated. version 1.1.4 is on pypi
autoprotocol-3.1.0 outdated. version 3.5.1 is on pypi
cvxcanon-0.0.21 outdated. version 0.0.23.4 is on pypi
cvxpy-0.3.1 outdated. version 0.4.0 is on pypi
funcsigs-1.0.0 outdated. version 1.0.2 is on pypi
hmmlearn-0.1.1 outdated. version 0.2.0 is on pypi
keras-0.3.2 outdated. version 1.0.2 is on pypi
latexcodec-1.0.1 outdated. version 1.0.3 is on pypi
nose-timer-0.5.0 outdated. version 0.6.0 is on pypi
numdifftools-0.9.14 outdated. version 0.9.16 is on pypi
paramz-0.1.5 outdated. version 0.5.5 is on pypi
pybtex-0.18 outdated. version 0.20.1 is on pypi
python-coveralls-2.5.0 outdated. version 2.7.0 is on pypi
pytools-2014.3.5 outdated. version 2016.1 is on pypi
schema-0.3.1 outdated. version 0.5.0 is on pypi …
```

Update the check-outdated script

---

appveyor.yml
conda-build-all
devtools/docker-build.sh
devtools/osx-build.sh
openmm/meta.yaml

[conda-build-all] by default upload package to main. Recipes can specify label
A meta.yaml can specify the channel to upload to within the extras section:
extras:
upload: rc
Then all builds of this package will be uploaded specified channel only.
Three default channels are now defined:
1. main
2. dev (development builds)
3. rc (release candidates)

Specify default upload label

---

conda-build-all

see discussion in #488 
Since we only want to use main, dev, rc for now, automatically detected development versions (eg. alpha, beta, rc1 and so on) will be moved to the dev label. This used to be pre before. So we should locate and move files in "pre" and move them to dev in the next step.
@jchodera please review.

[conda-build-all] pre-releases go to rc now.

---

msmb_data/bld.bat
msmb_data/build.sh
msmb_data/meta.yaml

This package puts a couple hundred MB of example molecular dynamics data into your python prefix's `share/msmb_data` directory. We provide an API to fetch this data in `msmbuilder`. Other packages can use this data by loading the files
```python
import sys
"{prefix}/share/msmb_data/{dataset}/...".format(prefix=sys.prefix, dataset='fs_peptide')
```

Release msmb_data v2.0

---

packmol/meta.yaml

[Packmol](http://www.ime.unicamp.br/~martinez/packmol/download.shtml) does not use a versioned release system, so the best thing to do here is to update the version number to be the latest update date of the source tarball (which was manually verified to be 2016.06.09).

[packmol] 2016.06.09 

---

progress_reporter/bld.bat
progress_reporter/build.sh
progress_reporter/meta.yaml

We use this in PyEMMA to unify the progress reportage no matter of the backend (Jupyter and console).
@jhprinz asked me to cut it out, so he can use it OPS too.
@stefdoerr you might be interested as well, since this version is now going to be maintained.

added progress_reporter lib.

---

conda-build-all
schema/meta.yaml

In part for the python 3 pledge, and to enable apps which depend on this to make their own py3k builds.

Update schema to 0.6.2, enable py3k builds

---

schema/meta.yaml

Fix leftover issues from #584.
@mpharrigan Patching this here should correctly replace the build on the omnia conda channel, yes?

Made version number string again in schema

---

openmmtools/meta.yaml

This restores the ability to build `win` packages of `openmmtools` for python 3.5, now that there are `openmm` packages available.

[openmmtools] Build win py3.5 packages

---

.travis.yml
appveyor.yml
conda-build-all
devtools/docker-build.sh
devtools/osx-build.sh

Changed conda-build-all to support conda-build 2.0 and pinned it in the scripts via the env variable "CONDA_BUILD", so we can easily change that.
Rationale: the new version supports to get version numbers dynamically and it provides lots of bug fixes. 
However we need to carefully test this. I ran several tests locally and it works so far. 
Should I also add a new dummy recipe in this PR (temporarily) to prove it does what it should?

Switch to conda build 2.0.1

---

openbabel/meta.yaml

I'm hoping the build goes through without any issues. If it does, will remove [WIP] tag. If not, then might take some effort to figure out what need to be fixed in version upgrade.

Bump version on openbabel to 2.4.0

---

.travis.yml

Fixes https://github.com/omnia-md/conda-recipes/issues/605
Travis has [updated its `osx` image](https://blog.travis-ci.com/2016-10-04-osx-73-default-image-live/), causing issues with the `osx` builds. 
This PR restores the old `xcode6.1` image, but that image will expire 31 Oct 2016, at which point we will need to update to at least `xcode6.4`

Specify old osx image (xcode6.1) to recover previous behavior

---

yank/meta.yaml

Updates YANK to 0.11.0
- Version number is now a string
- Fixed Schema dependency

Updating YANK to version 0.11.2

---

ambermini/meta.yaml

The MD5 hash on the github release tarbal keeps changing, this is causing all builds of ambermini to fail. This removes the MD5 check and updates build number to hopefully get the omnia channel to update is release

Critical fix for the  MD5 issue for ambermini

---

openmm/meta.yaml

I accidentally left the `force_upload: True` flag on after building and pushing the openmm 7.1.0 beta.

[openmm] Turn off Force flag

---

mdtraj/1208-find-zlib.patch
mdtraj/bld.bat
mdtraj/build.sh
mdtraj/meta.yaml

cc: #662 #634 #645 
For now, we need certain packages to still be built by the omnia build system until we migrate the build system to CentOS 6 for conda-forge compatibility.

[mdtraj] Add mdtraj 1.8.0 recipe temporarily until build system migrated to CentOS 6

---

.travis.yml
appveyor.yml
conda-build-all
devtools/docker-build.sh
devtools/osx-build.sh

Supercedes #670 by updating `linux`, `osx`, and `win` builds (though there are likely other problems with the appveyor build).

Don't pin conda-build to 2.0.1 due to API incompatibilities with 'conda'

---

deepchem/meta.yaml
openbabel/meta.yaml

The following package was still broken from the conda-build kerfluffle. 
* deepchem
The following package could not build due to other `conda` related problems:
* parmed 
* MD5 Mismatch, the tarball on GitHub changed its MD5 signature. 
* If a new version is cut, the MD5 will be updated and wont be an issue. 
* If we have to _rebuild_ the current version this will be a problem.
* cc @swail package maintainer in case this is important. 
All other packages were able to `conda build` without the placeholder length error. There were a few that could not build due to various other errors that seem to be program specific, and not related to the `conda` problems.
Its worth noting that the `nightli.es` would never have caught this since it does not actually try rebuilding packages unless the …

Rebuild packages from conda-build break

---

conda-build-all

This might address #690.
I am not sure if this is a valid thing to change, as I don't quite understand the rationale for adding the build dir as a channel in the first place.
We either need to:
1. not add the build dir (as in this PR), or
2. make sure that the build dir has the right structure, to avoid warnings about the lack of a noarch directory and crashes with the latest version of conda.

Don't add conda build dir as channel

---

conda-build-all

This adds python 3.6 builds without yet dropping python 3.4 support.

Add python 3.6 support (without yet dropping python 3.4 support)

---

conda-build-all

Numpy 1.10 is not available (at the moment?) in default channel, so we skip this combination for now. See #702

[conda-build-all] ignore combination py36 and np110

---

conda-build-all

Fixes #678
Added another exclude rule for python3.4 and np112, because of the lack
of packages for this combination.

[conda-build-all] added np112 to default Numpy versions.

---

sphinxcontrib-autodoc_doxygen/meta.yaml
sphinxcontrib-lunrsearch/meta.yaml

The `noarch` packages `sphinxcontrib-*` were causing problems with Python 3.6 builds because, even though they were `noarch`, anaconda foolishly cannot identify them as being available when Python 3.6 is in use. Removing `noarch` for now.

Don't build sphinxcontrib-* as noarch

---

conda-build-all

Builds that did not have NumPy as a requirement were not compiling due to the workaround for Py34/Np112 and Py36/Np110. This problem was pointed out in the original TODO for the workaround. Package names in the error messages were also not matched which is why I missed the logger outputs saying as much.
This PR corrects this problem by attempting to build with a more favorable NumPy version without redundantly running builds when NumPy is specified. Also matches attempted package name with proper Python version. Once merged, existing Python 3.6 builds will want to re-fire to get the changes into their PR.
Fixes #719, Partial resolution to #712 and #702

Fix failing builds on Py36 when NumPy is not Required

---

devtools/docker-build.sh
devtools/osx-build.sh
openmm/durole.patch
openmm/meta.yaml
openmm/run_test.py

Sphinx decided to no longer ship the fncychap LaTeX package starting in 1.5, but still make use of it. So to get it, we have to manually install it. It would probably be good to add this to the Docker image at some point.

Manually install LatTeX packages to build OpenMM docs

---

cvxpy/meta.yaml

CvxPy has some odd requirements that don't provide an unbroken chain of dependencies. this causes `setuptools` to try and fetch the dependencies instead of `conda-build` which causes the errors this fixes.

Fix cvxpy sloppy build reqs

---

coverage/build.bat
coverage/build.sh
coverage/meta.yaml

Distributing coverage 4.0.3 with omnia to fix python-coveralls in python 3.6 since it is pinned to this version of coverage.

Adding coverage 4.0.3 to the distibuted software to fix python-coveralls

---

conda-build-all

...by setting the property it actually derives it from.
Fixes #735 
This only fixes the new problem. We still cannot use `noarch_python` in our builds as it breaks the string formatting, but that itself might also be fixed in a later version of conda-build.

Fix the change conda-build made to the `noarch` property 

---

appveyor.yml
devtools/docker-build.sh
devtools/osx-build.sh

`--yes` and `--use-local` conflict in conda-build 2.1.6, no idea when it will be fixed, so pinning version to keep production moving

Pin conda-build to 2.1.5 until they fix it

---

lomap/meta.yaml

I updated the PyQt version required and the new Lomap git home page

Update Lomap recepie. PyQt4 is needed

---

parmed/meta.yaml

Since openmm is an optional dependency of parmed, can we remove the dependency?
We are deploying our own versions of openmm and meld built against specific cuda versions. Installing parmed from the omnia channel tries to pull in openmm, which leads to a conflict.

Remove parmed dependence on openmm

---

README.md
appveyor.yml
conda-build-all
devtools/docker-build.sh
devtools/osx-build.sh

* Made conda-forge top priority channel, omnia second
* Removed --no-chan-pri requirement
* Updated README to reflect changes
* Added "How to keep using only omnia" info to README
* Drops support for Python 3.4
xref: https://github.com/omnia-md/conda-recipes/pull/772#issuecomment-303382780
xref: #777, conda-forge/staged-recipes#3020

Make conda-forge highest priority channel

---

openforcefield/meta.yaml

With the `conda-forge` channel, sometimes `conda` installs `icu 56` (a dependency of `lxml`) and causes problems (`lxml` was build with `icu 58`). See open-forcefield-group/openforcefield#44.
This just bumps build number.

[openforcefield] 0.0.2-1: fix for conda-forge

---

devtools/osx-build.sh

Not sure what is wrong here, but something changed either in Homebrew or Homebrew-cask that made it so the -y option isnot accepted in `brew cask` anymore. I don't know if this is a bug or intentional yet and no one has raised an issue on either github, so I am writting in a || to try and error trap a bit for both cases.

-y option no longer valid in homebrew-cask?

---

appveyor.yml

Fixes #797
More of a work-around, but doing a full upgrade of conda-build may require much more work

Pin Windows to Conda-build 2.1.17

---

openforcefield/meta.yaml

Fixes https://github.com/open-forcefield-group/openforcefield/issues/63

[openforcefield] Pin networkx to 1.11 to avoid API-breaking 2.0

---

openmm/build.sh
openmm/meta.yaml

The `-DCMAKE` flags for OpenMM were redundant and causing optimization flags to not be set. This PR should fix this problem.
We have to trigger a new OpenMM build because of this setting. Will only affect the Unix based builds.
We're doing testing in the conda-dev-recipes repo right now to make sure this change has the desired affect first, this PR is in anticipation right now to run through the tests.
See discussion in pandegroup/openmm#1869 and omnia-md/conda-dev-recipes#107 for more details

Remove de-optimizing OpenMM CXX Flags

---

saltswap/meta.yaml

This still needed to be added before the premature merge of #823 .

Enable python 3 builds on win64 for saltswap

---

openforcefield/meta.yaml

Current version doesn't behave with modern networkx because we haven't done a new point release in months; I just created a new point release and this updates the recipe accordingly.
The repo has also moved.

Update openforcefield for 0.0.3

---

.travis.yml
devtools/osx-build.sh

This PR enables Travis' Caching feature to cache the CUDA Mac installers to speed up the OSX build time. The caching feature saves up to 20 min on the OSX builds.
I have also changed how the Homebrew/Cask update is handled to shave a few more minutes off the boot. I tried caching that as well, but ran into issues where it was not saving time.
Overall, this reduces the OSX boot time from ~40 min to 20 min.

Cache the Nvidia drivers on OSX to speed boot time

---

.travis.yml
openmm/meta.yaml
openmm/run_test.py

This PR makes some more changes in #837

Update omnia build system to CUDA 9.0 and force openmm 7.2 beta build

---

conda-build-all

To any meta.yaml file, add the entry:
```yaml
extra:
include_omnia_label: LABEL
```
where `LABEL` is replaced with any of the `STANDARD_LABELS` found in the `conda-build-all file`.
These tells the build script to prioritize searching in `-c omnia/label/LABEL` just behind `conda-forge`
so packages can build off of other omnia tags, such as beta.
This only searchs omnia tags to prvent someone from injecting nasty code from untrusted channels.
Enables #842 to proceed for OpenMM 7.2 beta testing
cc @jchodera @peastman
Could you both take a look at this and see if this makes sense for to you?

Enable ability for packages in Omnia to build against a specific label.

---

openmm/bld.bat
openmm/meta.yaml

Because *of course* using Windows style paths on Windows doesn't work correctly...

Fixed error building OpenMM on Windows

---

.travis.yml

See: https://blog.travis-ci.com/2017-12-12-new-trusty-images-q4-launch
This hopefully fixes the issue noted by @peastman in https://github.com/omnia-md/conda-recipes/pull/852#issuecomment-357307310

Use old travis trusty image since new one breaks our builds.

---

packmol/meta.yaml

Also drops the libgfortran 1.0 pin

Update packmol to 18.013

---

openmoltools/meta.yaml

This is the last Python 2.7 release for this package

Update OpenMolTools to 0.8.3

---

appveyor.yml
devtools/docker-build.sh
devtools/osx-build.sh

The actual fix is something I am working on so we have conda-build 3 compatibility and we can stop pinning to conda and conda-build, but many, many, many things changed and it will take a while to fix.
Since I don't know how long that will take, this is a stopgap to pin the conda version to stop this cycle of band-aid'ing while I get a proper fix in.

 Pin conda to a max to not break its API

---

fahmunge/meta.yaml

This enables `osx` builds for `fahmunge`.

[fahmunge] Build fahmunge for osx too

---

conda-build-all

This PR ensures that the source build tree is cleaned following build and upload of each package.
This helps eliminate repeated failures of the `osx` travis builds due to the instance running out of allocated disk space.

Clean source after each build

---

devtools/docker-build.sh
devtools/osx-build.sh

This PR updates the python and numpy build matrix to match [`conda-forge` availability of `numpy` packages](https://anaconda.org/conda-forge/numpy/files):
* Python 2.7, 3.6, 3.7
* NumPy 1.14, 1.15

Build python 2.7, 3.6, 3.7 and numpy 1.14, 1.15 to match conda-forge

---

shiftx2/meta.yaml

This job https://travis-ci.org/mdtraj/mdtraj/jobs/478463660 fails with 
```
conda.CondaMultiError: Conda detected a mismatch between the expected content and downloaded content
for url 'https://conda.anaconda.org/omnia/linux-64/shiftx2-1.10-py27_0.tar.bz2'.
download saved to: /home/travis/miniconda3/pkgs/shiftx2-1.10-py27_0.tar.bz2
expected md5 sum: 25ac9ccb5d3a91f50de198b9c767ad86
actual md5 sum: ecc17f52cf376b2bced5112bbdd01727
```
searching this repo for previous similar issues suggests that the fix for this is just to remove the md5sums from the package (https://github.com/omnia-md/conda-recipes/pull/700)?

Remove md5 from shiftx2 package?

---

.travis.yml
devtools/osx-build.sh

* Now that `xcode 6.4` has been deprecated:
I've updated builds to use [`xcode` 9.4](https://docs.travis-ci.com/user/reference/osx/#macos-version) and the target osx version to 10.10.
* We now install brew packages via the [`addons`](https://docs.travis-ci.com/user/installing-dependencies/#installing-packages-on-macos) mechanism
* Since CUDA-dependent builds have moved to https://github.com/omnia-md/conda-recipes-cuda, I've commented out the CUDA toolkit installation (and additional TeX package install) for `osx` since this was causing problems with the docker image.

Update osx builds: Use xcode 9.4, target osx 10.10, skip CUDA/additional tex package installs

---

openmmtools/meta.yaml

This moves the `pymbar` dependency from the `test` to `run` requirements as was brought up in choderalab/openmmtools#428 .

OpenMMTools 0.18.2 - build 1

---

smirnoff99frosst/meta.yaml

First live (not `rc`-tagged) build.

[smirnoff99Frosst] 1.0.9

---

devtools/osx-build.sh

https://openforcefieldgroup.slack.com/archives/C8NE3J96U/p1564504709107000
The omnia OSX travis jobs have started failing[1]. I started seeing this problem in my builds last night, and waited for the nightly cron job to run to see if it was just my PR, or if it was an overall problem. The cron job failed. So, I think it's a dependency that's changed. The most likely cause appears to be a new version of miniconda [2]. This miniconda release coincides with an update of the base conda to 4.7.10.
The cause of this error seems to be that the new miniconda builds a py37 environment (which it did before, no change there), but then dependencies resolve to more firmly pin python=3.7. Now, when we request an environment with conda install -yq 'conda<=4.3.34'[4], it is unable to downgrade …

make osx conda downgrade also pin python to 3.6

---

assaytools/meta.yaml
protons/meta.yaml

* [assaytools] skip py37 since pymc2 not available for py37
* [protons] skip, since broken

Fix travis failures

---

openforcefield_forcefields/meta.yaml

Rebuild now that there's both `openff-1.0.0-rc1` and `openff-hbonds-1.0.0-rc1`

[openforcefield_forcefields] 1.0.0-RC1 (label: rc, build 2)

---

openforcefield/meta.yaml

Build test for 0.5.1, to see if we can nab `omnia/label/dev openforcefields` in the recipe, or if we'll need to relabel the release candidate to `main`

[WIP] openforcefield 0.5.1

---

.travis.yml

Something has changed about how Travis parses environment variables. It's probably related to [this change](https://changelog.travis-ci.com/more-secure-handling-of-secure-values-in-configuration-126390). I can't totally follow what's wrong here, since the change didn't completely break parsing of our `.travis.yml`, but instead just seems to have garbled it.
Either way, this PR basically restructures our job-definition code, replacing the `matrix` keyword with the `jobs` keyword that seems to be prevalent in current docs.

fix build env definition

---

yank/meta.yaml

The older version of cerberus is not compatible with the new YANK anymore. This pins the package to version >= 1.3 and bumps the build number.

[yank] Bump build number and pin cerberus

---

openforcefield/meta.yaml
openmm-forcefields/build.sh
openmm-forcefields/meta.yaml
openmoltools/meta.yaml

This PR 
* Migrates `openforcefield` and `openmoltools` from depending on `ambermini` and `parmed` to just depending on the [new conda-forge `ambertools`](https://anaconda.org/conda-forge/ambertools/files) (which includes a recent `parmed`)
* Adds [`openmm-forcefields` 0.7.1](https://github.com/openmm/openmm-forcefields/releases/tag/0.7.1), though this will not work correctly for SMIRNOFF impropers unless the latest `omnia-dev` version of OpenMM is installed (which incorporates a critical extension https://github.com/openmm/openmm/pull/2511)

Migrate all ambermini dependencies to ambertools; add openmm-forcefields

---

openmmtools/meta.yaml

This removes another instance of `parmed` as a dependency, since it is now in `conda-forge` ambertools.
cc #1006

[openmmtools] use conda-forge ambertools to provide parmed

---

openmm-forcefields/build.sh
openmmforcefields/build.sh
openmmforcefields/meta.yaml

The discrepancy between `openmm-forcefields` and `openmmforcefields` was causing trouble, so this PR eliminates this issue.
I will delete the old `openmm-forcefields` packages from anaconda cloud.

[openmmforcefields] Rename package openmm-forcefields -> openmmforcefields

---

devtools/docker-build.sh
perses/meta.yaml

This updates the dependencies for `perses` to be consistent with the [current dependencies](https://github.com/choderalab/perses/blob/master/devtools/conda-recipe/meta.yaml).

[perses] 0.5.0 build 1 - update dependencies and allow openeye dependencies

---

assaytools/meta.yaml
devtools/docker-build.sh
devtools/osx-build.sh
perses/meta.yaml

This PR fixes issues with the `osx` build arising from the requirement for `openeye-toolkit` for `perses`.

[perses] 0.5.0 build 2 - fix issues with osx

---

openforcefields/meta.yaml

This will also contain the 1.0.1 release, but that won't get a separate package since they're being released simultaneously.

[openforcefields] 1.1.1

---

offline-builds/perses/meta.yaml

We can't use `noarch` since the `setup.py` contains an entry-point:
```
entry_points={
'openmm.forcefielddir' : ['perses=perses:get_datadir'],
'console_scripts' : ['perses-relative = perses.app.setup_relative_calculation:run','perses-fah = perses.app.fah_generator:run']
},
```
When you package with python 3.6, we end up with the entry point command-line executable that _only_ works if your environment is python 3.6:
```
#!/home/chodera/miniconda/envs/perses/bin/python3.6
import re
import sys
from perses.app.fah_generator import run
if __name__ == '__main__':
sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
sys.exit(run())
```
So it's not really noarch as a result.
This PR un-does the `noarch` from #1054.
I've manually built and uploaded the packages for python 3.6 and 3.7 …

[perses] Fix 0.7.1 

---

offline-builds/perses/meta.yaml

`dicttoxml` was accidentally omitted from build 3.

[perses] 0.7.1 build 4 - add missing dicttoxml dependency

---

offline-builds/perses/build.sh
offline-builds/perses/meta.yaml

Trying to see if we can get a noarch build that doesn't have the problems of builds 0 and 1.
Removed build.sh, moved pip install to meta.yaml, included entry points in meta.yaml
To test:
`conda create --yes -n temp_perses6 -c conda-forge -c omnia/label/rc -c omnia -c openeye perses`

[Perses] 0.7.1 build 6

---

offline-builds/fragmenter/meta.yaml

Fragmenter is incompatible with OE2020, per https://github.com/openforcefield/fragmenter/issues/61
Putting this up as a reminder -- Will build package and test next week.

[fragmenter] 0.0.4 build 1

---

offline-builds/fragmenter/meta.yaml

@jthorton just pointed out that 0.0.4 is no longer the latest version of fragmenter, and actually has a conflict with the latest CMILES currently on conda forge. He can fix it by installing the latest fragmenter from master. So I'm updating the version of this package to the newest tag (0.0.7)

[fragmenter] 0.0.7

---

offline-builds/openforcefields/meta.yaml

Per https://github.com/conda-forge/openff-forcefields-feedstock/pull/5, I'm manually making a `openforcefields` release with the sage release candidate, for the purposes of the conformer benchmarking project.

openforcefields-2.0.0-rc.1
