- pdbfixer/meta.yaml
> Added numpy requirement to pdbfixer recipe

- yank/build.sh
- yank/meta.yaml
> Updated YANK recipe to 1.0 and attempted to fix missing bin/yank script.

- pyhmc/meta.yaml
re: https://github.com/omnia-md/conda-recipes/pull/83#discussion_r22743340
> change other git@.. to https://..

- README.md
This follows @rmcgibbo's suggestion from #89
> Added Jenkins badges to README

- README.md
Here's an attempt to *label* the build status.
> Added identifying text to build status badges on README

- gaff2xml/meta.yaml
- openmmtools/meta.yaml
- yank/meta.yaml
I copied in the versions from their github devtools.  I also added some releases to openmmtools, yank, and gaff2xml so that we can actually have some version control on these binstar packages.
I also deleted *ALL* the yank packages on binstar because we had versions tagged 1.0 that were definitely NOT a 1.0 release.
> Updates to yank, openmmtools, and gaff2xml recipes

- openmm/bld.bat
- openmm/meta.yaml
- openmm/plugin-dir.patch
- openmm/post-link.bat
- openmm/post-link.sh
Reverts omnia-md/conda-recipes#116
> Revert "OpenMM post-link logic."

- pint/bld.bat
- pint/build.sh
- pint/meta.yaml
Conda recipe for pint physical quantities library. @kyleabeauchamp, can you check if this builds on your VM?
> Added recipe for Pint-0.6

- yank/build.sh
- yank/meta.yaml
This fixes some issues introduced in the latest version.
> Fix yank package

- schema/bld.bat
- schema/build.sh
- schema/meta.yaml
I would like to build this package so I can use it for my bayesian ITC code.
> Add schema recipe.

- assaytools/build.sh
- assaytools/meta.yaml
This PR adds a recipe for [assaytools](http://github.com/choderalab/assaytools).
> Added assaytools recipe

- openmm-dev/bld.bat
- openmm-dev/build.sh
- openmm-dev/meta.yaml
- openmm-dev/openmm-pr-780.patch
- openmm-dev/post-link.bat
- openmm-dev/post-link.sh
This is needed because of https://github.com/pandegroup/openmm/pull/817 and is intended to be temporary.
> Added openmm-dev recipe as a temporary workaround

- pyemma/meta.yaml
please merge ASAP, I need those conda packages! Thank you!
> [pyemma] updated to 1.1

- pyemma/meta.yaml
Hopefully nothing more than a trivial update is needed.
> Updated pyemma to 1.1.2

- pytram/bld.bat
- pytram/build.sh
- pytram/meta.yaml
This adds the recipe for pytram (http://github.com/markovmodel/pytram)
> added pytram

- pyhmc/meta.yaml
There are a bunch of packages that aren't
available?
ref: https://github.com/rmcgibbo/pyhmc/blob/master/devtools/conda-recipe/meta.yaml
> Don't run tests for pyhmc

- bhmm/build.sh
- bhmm/meta.yaml
This is an initial add of the bhmm 0.1.0 development release to work out conda packaging and distribution.
> Added bhmm recipe

- openmm/build.sh
- openmm/meta.yaml
This addresses https://github.com/pandegroup/openmm/issues/881
> Changed OpenMM recipe to build osx version with 10.7 SDK instead of 10.9

- appdirs/bld.bat
- appdirs/build.sh
- appdirs/meta.yaml
- boost/build.sh
- boost/meta.yaml
- pytools/bld.bat
- pytools/build.sh
- pytools/meta.yaml
- pyublas/build.sh
- pyublas/meta.yaml
- pyublas/run_test.py
- pyvisfile/build.sh
- pyvisfile/meta.yaml
- silo/build.sh
- silo/meta.yaml
I want to use http://mathema.tician.de/software/pyvisfile/ in a project I'm working on. Unfortunately it's a little tricky to compile all the dependencies, so I made conda packages so I don't have to do it again.
I'm not sure exactly if we've decided on the scope of this repo, but this seemed like a better place to put the recipes than anywhere else?
> pyvisfile and dependencies

- yank/meta.yaml
> Switch gaff2xml to openmoltools in yank recipe

- bhmm/meta.yaml
The tests are failing; not ready to merge.
> Updated BHMM recipe for 0.2.0

- parmed/bld.bat
- parmed/build.sh
- parmed/meta.yaml
> conda recipe for ParmEd

- bhmm/meta.yaml
> Increment bhmm to 0.3.0; fix bhmm weirdness

- yank/meta.yaml
This addresses https://github.com/choderalab/yank/issues/236
> [yank] Update recipe to use pymbar 2.1beta0 since not pymbar 3 compatible yet

- ensembler/meta.yaml
> Ensembler v1.0.2 release

- openmmtools/meta.yaml
This release uses the new `parmed` conda package.
> [openmmtools] 0.7.1 release uses parmed conda package

- .travis.yml
This fixes travis failures of the sort observed in #246
> Fix travis-ci failures

- ambermini/build.sh
- ambermini/meta.yaml
* fix tests
* compile with `gfortran` on Jenkins `osx`
> [ambermini] Updated recipe to 15.0.2

- bhmm/meta.yaml
We've recently split the BHMM part into its own toolkit (`bhmm`).
> [bhmm] Update to 0.4.0

- fftw3f/build.sh
Builds both static and dynamic libraries.
> Also build static libraries for fftw3

- LICENSE.txt
Add MIT license to conda-recipes.
> MIT License on the recipes

- devtools/appveyor/install.ps1
This should fix some appveyor issues.
> Update appveyor script for binstar -> conda-build and missing 'six' problems

- packmol/README.md
- packmol/bld.bat
- packmol/meta.yaml
> Fix windows packmol

- cclib/bld.bat
- cclib/build.sh
- cclib/meta.yaml
This adds a recipe for building cclib (parser for Gaussian quantum chemistry output files) version 1.3.1
> [cclib] Added cclib recipe

- conda-build-all
- nose-timer/bld.bat
- nose-timer/build.sh
- nose-timer/meta.yaml
- termcolor/bld.bat
- termcolor/build.sh
- termcolor/meta.yaml
Added recipes for `nose-timer` via `conda skeleton`, which is useful for timing nosetests.
> [nose-timer] and [termcolor] : Added recipes

- covar/bld.bat
- covar/build.sh
- covar/meta.yaml
https://pythonhosted.org/covar/
> Add covar package

- .travis.yml
- boost/build.sh
- conda-build-all
- devtools/docker-build.sh
- pyublas/build.sh
- pyvisfile/build.sh
- pyvisfile/meta.yaml
- silo/build.sh
https://travis-ci.org/rmcgibbo/conda-recipes
> Docker and OS X

- msmbuilder/meta.yaml
cc https://github.com/msmbuilder/msmbuilder/pull/685
> msmbuilder 3.3 doesn't work with sklearn 0.17

- progressbar/bld.bat
- progressbar/build.sh
- progressbar/meta.yaml
From https://github.com/conda/conda-recipes/tree/master/progressbar, since somehow that package is no longer be maintained in the main anaconda channel.
> [progressbar] Add progressbar from conda/conda-recipes

- openmm/meta.yaml
cc: https://github.com/pandegroup/openmm/issues/1307
> [openmm] OpenMM 6.3.1 release

- conda-build-all
- sphinxcontrib-autodoc_doxygen/bld.bat
- sphinxcontrib-autodoc_doxygen/build.sh
- sphinxcontrib-lunrsearch/bld.bat
- sphinxcontrib-lunrsearch/build.sh
> Fix uploading of noarch-python packages

- conda-build-all
> Attempting to fix conda upload for non-noarch packages

- pyhmc/meta.yaml
Let's see if this works / why it doesn't work
> Build pyhmc on windows

- keras/meta.yaml
Includes some critical bugfixes.
> Bump keras version to 0.3.2

- nglview/bld.bat
- nglview/build.sh
- nglview/meta.yaml
- simpletraj/bld.bat
- simpletraj/build.sh
- simpletraj/meta.yaml
> added nglview and simpletraj

- bhmm/meta.yaml
> BHMM release 0.6.1

- simpletraj/meta.yaml
> [simpletraj] Skip win build

- conda-build-all
> Fix the channels issue

- .travis.yml
- devtools/docker-build.sh
- devtools/osx-build.sh
Addresses https://github.com/omnia-md/conda-recipes/issues/450
Also upgrades `osx` CUDA to 7.5
> OSX travis build fixes: Update to CUDA 7.5, add latex

- osprey/bld.bat
- osprey/build.sh
- osprey/meta.yaml
built with conda-build skeleton
> add osprey

- gpy/meta.yaml
re: https://github.com/omnia-md/conda-recipes/pull/458#issuecomment-193073489
> skip win and py34 build for gpy

- gpy/0001-Add-basesetup.py.patch
- gpy/0002-Add-compiler-detection-code-for-OpenMP.patch
- gpy/0003-Fix-rb-for-Python-3.patch
- gpy/bld.bat
- gpy/meta.yaml
This should fix the gpy problems from #458
> Fix gpy stuff

- openmm/bld.bat
- openmm/build.sh
- openmm/meta.yaml
I believe this should build and be pushed to the `pre` channel because the version number has `rc` in it.
> [openmm] 7.0rc1

- msmbuilder/meta.yaml
And sync requirements with our CI requirements
> Release msmbuilder 3.4

- conda-build-all
- nglview/meta.yaml
> Fix bug in nglview recipe that led to parser error

- eigen3/build.sh
- eigen3/meta.yaml
- eigen3/run_test.sh
- eigen3/test.cc
@jchodera you previously copied the `eigen3` package to the omnia channel, but this was just the linux version. We might as well build our own for both mac and linux.
> Add eigen3

- conda-build-all
> Send packages to "rc" label by default. Support "--dev"

- mdtraj/meta.yaml
Is it just me or did the pypi urls get long?
> Release MDTraj 1.7

- appveyor.yml
- devtools/docker-build.sh
- devtools/osx-build.sh
> Check against omnia/label/rc

- rdkit/meta.yaml
cc: https://github.com/omnia-md/conda-recipes/issues/512#issuecomment-216631019
> [rdkit] Require boost ==1.59

- pyemma/meta.yaml
Removed mdtraj win32 pytables workaround.
> [pyemma] version bump 2.2.

- openmm/meta.yaml
See https://github.com/pandegroup/openmm/issues/1489
> [openmm 7.0.1] build based on git hash 5e86c4f

- conda-build-all
Fixes https://github.com/omnia-md/conda-recipes/issues/535
> Fix handling of 'extras' section in meta.yaml

- schema/meta.yaml
> Update schema from 0.3.1 to 0.5.0 version

- openmoltools/meta.yaml
This fixes some issues with using openmm 7.0rc1
> [openmoltools] Use OpenMM 7.0.1 (instead of 7.0rc1)

- yank/meta.yaml
> [yank] release 0.9.0

- osprey/meta.yaml
not sure why v1.0 is not already on the Omnia channel (since https://github.com/omnia-md/conda-recipes/pull/547), but @rasbt [ran into trouble](https://github.com/openjournals/joss-reviews/issues/34#issuecomment-236322758) while reviewing out JOSS submission
> build Osprey v1.0

- conda-build-all
cc: https://github.com/omnia-md/conda-recipes/issues/561
This is needed for https://github.com/omnia-md/conda-dev-recipes
> Allow --force flag to avoid eliminating packages on anaconda.org from build list

- corner/bld.bat
- corner/build.sh
- corner/meta.yaml
need [corner.py](https://github.com/dfm/corner.py) for https://github.com/omnia-md/conda-recipes/pull/577
> add corner.py

- osprey/meta.yaml
> Update Osprey meta.yaml

- pytest/bld.bat
- pytest/build.sh
- pytest/meta.yaml
Until we have this version upstream, I'd like to add it here. I will take of the removal then.
> added pytest-3.0.2

- openpathsampling/meta.yaml
- openpathsampling/requirements.txt
Now to see whether I'm doing this correctly....
> [openpathsampling] 0.9.1

- sams/build.sh
- sams/meta.yaml
> [sams] 0.1.0

- sams/meta.yaml
This should fix the appveyor builds
> [sams] skip win

- yank/build.sh
- yank/meta.yaml
Preparation for creating a new yank-examples repo in a future PR
> Adding YANK 0.12.0, removed examples from main repo

- .travis.yml
Fixes https://github.com/omnia-md/conda-recipes/issues/608
> Update travis osx to 10.10 and xcode 6.4 to fix osx build issues

- msmexplorer/meta.yaml
re: https://github.com/msmexplorer/msmexplorer/issues/68
> remove msmexplorer tests

- .travis.yml
I had a great deal of difficulties with http://omnia-md/conda-dev-recipes, so I'm doing the same thing here to restore push functionality.
> Remove secure BINSTAR_TOKEN and set through UI instead

- openpathsampling/meta.yaml
[OpenPathSampling 0.9.2](https://github.com/openpathsampling/openpathsampling/releases/tag/v0.9.2)
> [openpathsampling] 0.9.2

- smarty/meta.yaml
- solvationtoolkit/meta.yaml
Addresses #649 by removing skip
> Remove py3 skip for smarty, solvationtooliit

- .travis.yml
- openmm/build.sh
Testing for now.
cc: https://github.com/pandegroup/openmm/pull/1697
> [openmm] 7.1.0 beta build with clang

- progress_reporter/meta.yaml
Fixes issue noted by https://github.com/omnia-md/conda-recipes/pull/657#issuecomment-270964966
> [progress_reporter] Remove skip for different platforms since we no longer use noarch

- smarty/meta.yaml
Update meta.yaml for smarty to current version (we'd forgotten to do this in a while).
@limn1, this would fix your issue.
> New smarty release

- openbabel/meta.yaml
#677 is not building because OpenBabel is not building. I think this is a chicken-egg problem so I am going to try and build and push openbabel first, then come back for deepchem.
> Building openbabel first, will come back for deepchem

- openbabel/meta.yaml
> Added version epoch to the OpenBabel meta.yaml file

- devtools/osx-build.sh
Revert to previous version of doxygen from homebrew.
> Fix doxygen segfault on osx

- openmm/bld.bat
This is designed to be used in the Vagrant VM at https://github.com/pandegroup/openmm/tree/master/devtools/packaging/scripts/windows.
> New Windows build script for OpenMM

- yank/meta.yaml
> fix hdf4 error

- README.md
- conda-build-all
- parmed/meta.yaml
> Remove md5 hash from parmed recipe

- scs/run_test.py
@rmcgibbo as the one who added the original scs, do these changes look good to you?
> Fix the tests for scs to work with numpy 1.12

- sphinxcontrib-autodoc_doxygen/meta.yaml
> Update sphinx version to get better openssl

- openbabel/meta.yaml
- openmm/meta.yaml
Matching issues is openbabel/openbabel#372. I'm keeping an eye on it.
> Turn off Open babel for python 3.6 until its fixed

- openmoltools/meta.yaml
Minor maintenance update that I need conda-installable for orion.
> Update to new release of openmoltools

- nglview/meta.yaml
> Fix version number for conda recipie

- molpx/meta.yaml
> molpx v0.1.4

- clusterutils/meta.yaml
> Bump clusterutils to 0.2.0

- clusterutils/meta.yaml
> Bump clusterutils to 0.3.0

- openmmtools/meta.yaml
> [openmmtools] Bump to 0.9.0

- openmmtools/meta.yaml
This is a bugfix release for Python 2 including choderalab/openmmtools#150 .
> [openmmtools] Bugfix release - bump to 0.9.1

- openmmtools/meta.yaml
Updates the version of openmmtools.
> Openmmtools release 0.9.2

- openmmtools/meta.yaml
Update the package version to 0.9.3
> openmmtools-0.9.3

- msmbuilder/meta.yaml
> msmbuilder 3.8.0

- deepchem/meta.yaml
> deepchem 1.1.0

- openforcefield/meta.yaml
> update openforcefield recipe

- openmmtools/meta.yaml
Release 0.10.0 for OpenMMTools.
> [openmmtools] 0.10.0

- openmmtools/meta.yaml
Closes choderalab/openmmtools#228
> Bump OpenMMTools to 0.11.0

- devtools/osx-build.sh
This tries to pin to a specific repository to avoid getting an error because the CTAN repo is out of date.
Fixes #789
> Pin to texlive repository

- devtools/docker-build.sh
- devtools/osx-build.sh
See #799
We will need to make major changes to our build environment before we move to conda-build 3
> Pin Conda-build 2.1.17 everywhere

- openmmtools/meta.yaml
Bugfix release 0.12.1 for openmmtools
> [openmmtools] 0.12.1

- devtools/docker-build.sh
- devtools/osx-build.sh
- yank-examples/meta.yaml
> Update yank-examples to 1.1

- yank/meta.yaml
> Update YANK to 0.18.0

- saltswap/bld.bat
- saltswap/build.sh
- saltswap/meta.yaml
This PR adds a conda recipe for the saltswap package by @gregoryross.
> Add recipe for saltswap v0.5.1

- saltswap/meta.yaml
This updates the recipe to the latest release.
> Update saltswap to 0.5.2

- saltswap/meta.yaml
Accidentally left out closing ] has been added.
> Fix bug in saltswap meta.yaml

- yank/meta.yaml
Change YANK's source scheme to reduce download time
> Bump YANK to 0.19.1

- openmm/build.sh
- openmm/meta.yaml
@peastman : Take a look? I've merged in changes to this recipe from [the `dev` recipe](https://github.com/omnia-md/conda-dev-recipes/tree/master/openmm).
> [openmm] OpenMM 7.2 beta build

- pdbfixer/meta.yaml
@Lnaden could you confirm my changes are correct to generate the beta of 1.5?
> Update PDBFixer to 1.5

- openmm/meta.yaml
- openmm/run_test.py
@jchodera @Lnaden is this correct, or do I also have to set `force_upload` to `True`?
> Build OpenMM 7.2rc2

- openpathsampling/meta.yaml
[OpenPathSampling 0.9.4](https://github.com/openpathsampling/openpathsampling/releases/tag/v0.9.4)
> [openpathsampling] 0.9.4

- conda-build-all
As title says. Fixes #867
As this is a critical fix to a print statement only, I am going to merge this right away so builds can be started ASAP. I tested locally, its fine.
> Fix string formatting for multi-channel package

- openforcefield/meta.yaml
- solvationtoolkit/meta.yaml
> Update openforcefield for 0.0.4

- protons/bld.bat
- protons/build.sh
- protons/meta.yaml
A recipe for protons has been added. It points to the pre-release
version available on github.
> Add protons pre-release package

- fahmunge/meta.yaml
Update `fahmunge` for 0.3.0 release.
>  [fahmunge] 0.3.0

- fahmunge/meta.yaml
This should hopefully fix the appveyor failures.
> [fahmunge] Don't build fahmunge on win

- skorch/0001-Compatibility.patch
- skorch/bld.bat
- skorch/build.sh
- skorch/meta.yaml
- skorch/run_test.py
Adding skorch library and patching it to be used with osprey
> add skorch

- conda-build-all
- devtools/docker-build.sh
- devtools/osx-build.sh
- perses/meta.yaml
* Update perses to 0.2.0
* Include `omnia/label/dev` in channels
* Update `conda-build-all` to support pushing to multiple labels
> Perses 0.2.0

- openpathsampling/README.md
- openpathsampling/meta.yaml
Update for the most recent release (probably the last before 1.0!)
> [openpathsampling] 0.9.6

- eigen3/meta.yaml
- forcebalance/meta.yaml
- openmm-setup/meta.yaml
- openmm-setup/remove-requirements.patch
- perses/meta.yaml
- yank/meta.yaml
Fixes `yank`, `eigen3`, `forcebalance`, and `openmm-setup` builds
> Fixing more  py37 build failures

- openforcefield/build.sh
- openforcefield/meta.yaml
@j-wags: I've updated the recipe to build and bundle the HTML docs into `$MINICONDA/docs/openforcefield/html`
> [openforcefield] 0.2.1 ; now bundle HTML docs

- parmed/meta.yaml
@swails : Can you check if this looks right to you? No changes in dependencies, right?
cc: https://github.com/ParmEd/ParmEd/tree/3.2.0
> [parmed] 3.2.0

- openforcefield/meta.yaml
@jchodera -- Could you review?
> [openforcefield] 0.2.2

- openpathsampling/meta.yaml
> OpenPathSampling 1.0

- fragmenter/meta.yaml
> [fragmenter] 0.0.3

- openforcefield/meta.yaml
Adds requests and notebook as dependencies.
@jchodera Any objections? This will make the install slightly larger, but users currently have to install these separately to run all examples.
> [openforcefield] 0.5.1 build 1

- propertyestimator/meta.yaml
> [propertyestimator] 0.0.6 (label: main)

- propertyestimator/meta.yaml
> [propertyestimator] 0.0.7 (label: main)

- propertyestimator/meta.yaml
cc @j-wags - it looks like things work ok with the latest version of the toolkit, so I'm lifting the toolkit version pin.
> [propertyestimator] 0.0.7 build 1 (label: main)

- propertyestimator/meta.yaml
> [propertyestimator] 0.0.7 build 2 (label: main)

- forcebalance/meta.yaml
https://github.com/leeping/forcebalance/blame/master/devtools/conda-envs/test_env.yaml
> [forcebalance] 1.7.0 build 0

- propertyestimator/meta.yaml
> [propertyestimator] 0.0.8 build 0 (label: main)

- openmoltools/meta.yaml
> [openmoltools] Upgrade to 0.8.5

- openmoltools/meta.yaml
Now with 100% fewer awful bondtype warnings.
> [openmoltools] 0.8.6

- perses/meta.yaml
> mini release 

- yank/meta.yaml
This is until choderalab/pymbar#320 has been fixed.
> [yank] Temporarily pin pymbar to 3.0.3

- openmoltools/meta.yaml
> [openmoltools] 0.8.7

- openmmforcefields/meta.yaml
> [openmmforcefields] 0.7.3

- openforcefield/meta.yaml
> [openforcefield] 0.7.0 build 3

- openforcefield/meta.yaml
> [openforcefield] 0.7.0 build 4

- openmmforcefields/meta.yaml
Adds support for `openforcefield` 0.7.1
> [openmmforcefields] 0.8.0

- offline-builds/perses/meta.yaml
Adding `fire` and `joblib` dependencies
> Perses 0.8.0 release

- offline-builds/perses/meta.yaml
> Perses 0.8.1 release
